#!/bin/bash
set -o errexit -o nounset -o pipefail

readonly BUILD_ROOT=${1:-openwrt}

cat config >> "${BUILD_ROOT}/.config"
cp --recursive 'files' "${BUILD_ROOT}/"

cd "${BUILD_ROOT}"
./scripts/feeds update -a
./scripts/feeds install -a
make --jobs="$(($(nproc) + 1))" defconfig download clean world
